language: node_js

node_js:
  - "4"
  - "6"
  - "7"

sudo: false

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"

script:
  - (cd packages/eslint-plugin-jest && yarn link)
  - yarn link eslint-plugin-jest
  - yarn run test-ci
